# Generated by Django 3.2.9 on 2021-11-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('sleeping_place', models.CharField(max_length=100, verbose_name='Количество спальных мест')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за сутки')),
                ('descriptiion', models.TextField(blank=True, default=None, max_length=2500, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Аппартаменты',
            },
        ),
        migrations.CreateModel(
            name='AppartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('appartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.appartment', verbose_name='Аппартаменты')),
            ],
            options={
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
