# Generated by Django 3.2.9 on 2021-12-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('sleeping_place', models.CharField(max_length=100, verbose_name='Количество спальных мест')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за сутки')),
                ('descriptiion', models.TextField(blank=True, default=None, max_length=2500, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.SlugField(max_length=100, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Аппартаменты',
                'verbose_name_plural': 'Аппартаменты',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('date_start', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата заезда')),
                ('date_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата выезда')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='AppartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('appartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.appartment', verbose_name='Аппартаменты')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
