# Generated by Django 3.2.9 on 2021-11-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appartment',
            options={'verbose_name': 'Аппартаменты', 'verbose_name_plural': 'Аппартаменты'},
        ),
        migrations.AlterModelOptions(
            name='appartmentimage',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
