# Generated by Django 3.2.9 on 2021-12-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_appartment_show_in_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=300, verbose_name='Адрес'),
        ),
    ]
