# Generated by Django 3.2.9 on 2021-11-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата заезда'),
        ),
    ]
