# Generated by Django 3.2.9 on 2021-12-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_application_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
