# Generated by Django 3.2.9 on 2021-12-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211206_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Адрес'),
        ),
    ]
